// Compact wire v1: immutable position tables, independent of the readable business protocol (protocol.js).
// Never reorder/reuse a message id, enum value or record field in a published version. See docs/WIRE_PROTOCOL.md.
// A string field is raw JSON; [name, type] uses a record name, ['list', type], ['map', type], or ['enum', name].

export const WIRE_VERSION = 1;

export const WIRE_ENUMS = Object.freeze({
  phase: Object.freeze(['LOBBY', 'INFO_CHECK', 'BAND_DRAFT', 'BATTLE_CHECK', 'ROUND_START', 'SP_DRAFT', 'PREP',
    'COMBAT', 'UNITE', 'SETTLE', 'FINAL_ASSAULT', 'HIDDEN_CORE', 'RESULT']),
  difficulty: Object.freeze(['FUNNY', 'NORMAL', 'HARD', 'ABYSS']),
  mode: Object.freeze(['solo', 'coop']),
  combatMode: Object.freeze(['client', 'server']),
  status: Object.freeze(['left', 'dead', 'ready', 'deciding', 'acting', 'combat', 'done', 'helping']),
  fieldKind: Object.freeze(['normal', 'unite', 'boss', 'hidden']),
  family: Object.freeze(['bounty', 'supply', 'shop', 'tactic']),
  pieceKind: Object.freeze(['chess', 'item', 'token', 'bounty', 'tactic']),
  dir: Object.freeze(['UP', 'RIGHT', 'DOWN', 'LEFT']),
});

const list = (type) => ['list', type];
const map = (type) => ['map', type];
const en = (name) => ['enum', name];

/** @type {Record<string, any[]>} */
export const WIRE_RECORDS = {
  publicPlayer: ['playerId', 'seat', 'name', 'isBot', 'connected', 'alive', 'lp', 'bandId', 'shopLevel', 'boardCount',
    'ready', ['bonds', list('bond')], 'fieldId', ['status', en('status')], 'autoplay', 'pendingLp', 'uniteLeft'],
  bond: ['bondId', 'count', 'active', 'tier', 'layers', 'harmony', 'off', 'thresholds', 'countsHand'],
  field: ['fieldId', ['kind', en('fieldKind')], 'players', 'live', ['progress', 'progress']],
  progress: ['killed', 'resolved', 'total', 'done'],
  poolGroup: ['id', 'playerIds', 'scale'],
  hpPool: ['hp', 'max'],
  rerollVote: ['id', 'proposerId', 'voters', 'agreed'],
  bandDraft: ['id', ['groups', list('bandGroup')], 'order', 'turn', 'picks', 'skipsLeft', 'turnDeadline', 'turnSeconds', 'untimed'],
  bandGroup: ['id', 'playerIds', 'order', 'turn', 'picks', 'skipsLeft', 'turnDeadline', 'turnSeconds', 'untimed', 'done'],
  spDraft: ['id', ['groups', list('spGroup')], ['family', en('family')], 'name', 'desc', 'eventId', ['cards', list('card')],
    'order', 'turn', 'picks', 'taken', 'untimed', 'turnDeadline', 'turnSeconds'],
  spGroup: ['id', 'playerIds', 'order', ['family', en('family')], 'name', 'desc', 'eventId', ['cards', list('card')],
    'turn', 'picks', 'taken', 'turnDeadline', 'turnSeconds', 'untimed', 'done'],
  card: ['idx', ['kind', en('pieceKind')], 'id', 'name', 'desc', 'tier', 'descRaw', 'coin', 'payout', 'rounds', 'enemyKey',
    'count', 'price', 'team', 'tacticKind'],
  unite: ['helpers', 'leakers', 'round', 'roundsMax', ['skipVote', 'skipVote']],
  skipVote: ['id', 'eligible', 'voters', 'needed', 'passed', 'open'],
  uniteResult: ['through', 'helpers', 'leakers', 'losses'],
  seat: ['seat', 'playerId', 'name', 'isBot', 'ready', 'connected'],
  spectator: ['playerId', 'name', 'connected'],
  fieldMate: ['playerId', 'name', 'side'],
  roomSummary: ['code', ['mode', en('mode')], ['difficulty', en('difficulty')], 'capacity', 'playerCount', 'humanCount',
    'botCount', 'inMatch', 'joinable', 'hostOnline', 'disconnectedRetained', 'createdAt'],
  shop: ['level', 'maxLevel', 'upgradePrice', 'refreshPrice', 'freeRefreshes', 'frozen', ['slots', list('shopSlot')],
    ['rewardOffer', 'rewardOffer']],
  shopSlot: [['kind', en('pieceKind')], 'id', 'price', 'basePrice', 'sold', 'frozen'],
  rewardOffer: ['tier', 'source', 'label', 'queued', ['slots', list('shopSlot')]],
  piece: ['uid', ['kind', en('pieceKind')], 'id', 'golden', 'tier', ['items', list('item')], 'count', 'ownerUid', 'row', 'col', ['dir', en('dir')]],
  item: ['uid', 'id'],
  effect: ['id', 'name', 'desc', 'iconKind', 'iconId', 'counter', 'counterText'],
  enemyPreview: ['enemyKey', 'count', 'tag', 'start'],
  loadout: ['skill', 'module'],
  ops: ['potential', 'cultivate'],
  diy: ['charId', 'skillIndex', 'uniEquipId'],
  personalChoice: ['id', 'round', 'sourceItemId', ['cards', list('card')]],
  bossMate: ['playerId', 'side', ['units', list('unit')]],
  stats: ['dmgDealt', 'kills', 'leaks', 'gold', 'refreshes', 'merges', 'itemsEquipped', 'bossDamage', 'activatedLayers', 'lpLost', 'perfectRounds'],
  rect: ['r0', 'r1', 'c0', 'c1'],
  unit: ['id', 'kind', 'side', 'ownerId', 'defId', 'name', 'tier', 'golden', 'spine', 'avatar', 'x', 'y', 'facing',
    ['dir', en('dir')], 'maxHp', 'skillIndex', 'moduleId', 'items', 'form', 'potential', 'cultivate', 'standInFor', ['diy', 'diy']],
  unitStats: ['id', 'uid', 'defId', 'hp', 'alive', 'maxHp', 'atk', 'def', 'res', 'interval', 'blockCnt', 'moveSpeed',
    'range', ['base', 'unitStatsBase'], ['dir', en('dir')]],
  unitStatsBase: ['maxHp', 'atk', 'def', 'res', 'interval', 'blockCnt', 'moveSpeed', 'range'],
  moveTarget: ['area', 'row', 'col', 'idx'],
  battleSpec: ['v', 'battleId', 'fieldId', ['kind', en('fieldKind')], 'seed', 'modeId', 'round', 'stageId', ['rect', 'rect'],
    'timeLimit', ['players', list('battlePlayer')], 'spawns', 'routes', 'flags', 'enemyOverrides', 'waveId', 'bossId', 'content', ['boss', 'specBoss']],
  specBoss: ['poolHp', 'poolMax'],
  battlePlayer: ['playerId', 'seat', 'side', 'colOffset', ['units', list('battlePiece')], ['bonds', map('specBond')],
    'bandId', ['playerEffects', list('playerEffect')], 'deviceOverrides'],
  specBond: ['count', 'active', 'tier', 'layers'],
  playerEffect: ['id', 'key', 'source', 'params', 'counter', 'data'],
  battlePiece: ['uid', ['kind', en('pieceKind')], 'chessId', 'tokenId', 'row', 'col', ['dir', en('dir')], 'items',
    'skillIndex', 'moduleId', 'potential', 'cultivate', 'ownerUid', 'standIn', ['diy', 'diy'], 'carryState'],
  battleResult: ['time', 'reason', 'killed', 'resolved', 'total', ['perPlayer', map('battlePlayerResult')],
    'errors', 'unspawned', 'bossHpLeft'],
  battlePlayerResult: ['killed', 'total', ['leaked', list('leaked')], 'perfect', 'killedInTotal', 'leakedInTotal',
    'layerGains', 'coins', 'damageDealt', 'bossDamage', 'healingDone', 'deaths', ['unitsEnd', list('unitEnd')],
    ['unitStats', list('unitScore')], 'resolved'],
  leaked: ['enemyKey', 'mods', 'lpr', 'sourcePlayerId', 'tag', 'counted', 'boss', 'spawned'],
  unitEnd: ['uid', 'id', 'defId', 'hpPct', 'sp', 'skillActive', 'alive'],
  unitScore: ['id', 'uid', 'defId', 'name', 'kind', 'dmg', 'kills', 'heal', 'taken', 'attacks'],
  resultPlayer: ['playerId', 'seat', 'name', 'isBot', 'left', 'alive', 'victory', 'roundsPassed', 'eliminatedRound', 'lp', 'bandId',
    ['lineup', list('lineup')], ['bonds', list('bond')], ['stats', 'stats'], ['title', 'title'], 'trophies', 'reward'],
  lineup: ['id', 'golden', 'tier', 'row', 'col', 'items', ['diy', 'diy'], 'standInFor'],
  title: ['id', 'name', 'picId', 'text'],
};

// IDs are explicit so adding/reordering validators in protocol.js cannot accidentally change the wire.
// Root fields begin with rid. t is represented by the message id, never another position.
/** @type {Array<[number, string, 's2c'|'c2s', any[]]>} */
export const WIRE_MESSAGES = [
  [0, 'welcome', 's2c', ['playerId', 'token', 'name', 'serverNow', 'version', 'resumed', 'diyKitted', 'wire']],
  [1, 'ok', 's2c', []],
  [2, 'error', 's2c', ['code', 'msg', 'detail']],
  [3, 'pong', 's2c', ['c', 's']],
  [4, 'announcement.notice', 's2c', ['id', 'revision', 'msgid', 'createdAt', 'expiresAt']],
  [5, 'lobby.state', 's2c', ['online', 'roomCount', 'matchCount', 'joinableCount', ['rooms', list('roomSummary')], 'page', 'pageSize', 'totalPages']],
  [6, 'room.state', 's2c', ['code', 'hostId', 'maxAiPerRoom', ['mode', en('mode')], ['difficulty', en('difficulty')],
    'capacity', 'aiPicksLast', 'inMatch', ['seats', list('seat')], ['spectators', list('spectator')]]],
  [7, 'room.closed', 's2c', ['reason']],
  [8, 'm.public', 's2c', [['phase', en('phase')], 'round', 'lastRound', 'deadline', 'serverNow', 'modeId', ['difficulty', en('difficulty')],
    'stageId', 'setupRevision', ['rerollVote', 'rerollVote'], 'factions', 'disabledBonds', 'drawnDisabledBonds', 'bannedChess',
    'bossId', 'hiddenBossId', 'bossRound', 'hiddenRound', 'spRound', 'playerCount', ['poolGroups', list('poolGroup')],
    ['combatMode', en('combatMode')], 'paused', ['players', list('publicPlayer')], ['fields', list('field')], 'teamLp', 'overtimeAt',
    ['bossHp', 'hpPool'], ['draft', 'bandDraft'], ['sp', 'spDraft'], ['unite', 'unite'], ['uniteResult', 'uniteResult']]],
  [9, 'm.private', 's2c', ['playerId', 'seat', 'alive', 'lp', 'funds', 'bandId', 'ready', 'canReady', ['personalChoice', 'personalChoice'],
    ['shop', 'shop'], ['hand', list('piece')], ['temp', list('piece')], ['board', list('piece')], 'deployCap', 'deployCount',
    ['bonds', list('bond')], ['effects', list('effect')], ['nextEnemies', list('enemyPreview')], ['loadout', map('loadout')],
    ['ops', map('ops')], 'standIns', ['diy', map('diy')], 'diyBanned', ['bossMate', 'bossMate'], ['stats', 'stats']]],
  [10, 'm.field', 's2c', ['fieldId', ['kind', en('fieldKind')], ['rect', 'rect'], 'stageId', ['units', list('unit')],
    ['effects', list('effect')], 'prep', ['nextEnemies', list('enemyPreview')], 'side', ['mate', 'fieldMate'], 'live', 'players', 'sides']],
  [11, 'm.toast', 's2c', ['kind', 'text', 'msgid', 'params']],
  [12, 'm.ticker', 's2c', ['text', 'id', 'type', 'priority', 'playerId', 'args', 'msgid', 'params']],
  [13, 'm.emote', 's2c', ['playerId', 'id']],
  [14, 'm.result', 's2c', ['victory', 'roundsPassed', 'hiddenReached', 'hiddenCleared', 'reason', 'teamLp', 'modeId',
    ['difficulty', en('difficulty')], 'stageId', 'bossId', 'hiddenBossId', 'seed', 'durationMs', ['players', list('resultPlayer')], 'playerId']],
  [15, 'm.unitStats', 's2c', ['seq', 'round', ['units', list('unitStats')]]],
  [16, 'b.start', 's2c', ['battleId', 'fieldId', ['kind', en('fieldKind')], ['spec', 'battleSpec'], 'authoritative',
    'startAt', 'serverNow', 'elapsed', 'speed', 'watch', 'done']],
  [17, 'b.pool', 's2c', ['hp', 'max', 'teamLp', 'acked']],
  [18, 'b.end', 's2c', ['battleId', 'fieldId', 'reason']],
  [19, 'b.snap', 's2c', ['fieldId', 'gt', 'units', 'bossHp', 'stand', 'standCut']],
  [20, 'b.ev', 's2c', ['fieldId', 'gt', 'ev']],
  [32, 'hello', 'c2s', ['name', 'token', 'version', 'noReplace', 'claimAt', 'wire']],
  [33, 'ping', 'c2s', ['c']],
  [34, 'lobby.watch', 'c2s', ['on', 'list', 'page']],
  [35, 'lobby.quickMatch', 'c2s', ['capacity']],
  [36, 'room.create', 'c2s', [['mode', en('mode')], ['difficulty', en('difficulty')], 'capacity']],
  [37, 'room.join', 'c2s', ['code']],
  [38, 'room.leave', 'c2s', []],
  [39, 'room.ready', 'c2s', ['ready']],
  [40, 'room.setDifficulty', 'c2s', [['difficulty', en('difficulty')]]],
  [41, 'room.setCapacity', 'c2s', ['capacity']],
  [42, 'room.setAiPicksLast', 'c2s', ['on']],
  [43, 'room.addBot', 'c2s', []],
  [44, 'room.removeBot', 'c2s', ['seat', 'playerId']],
  [45, 'room.kick', 'c2s', ['seat', 'playerId']],
  [46, 'room.transferHost', 'c2s', ['playerId']],
  [47, 'room.start', 'c2s', []],
  [48, 'room.rerollSetup', 'c2s', ['setupRevision']],
  [49, 'room.cancelReroll', 'c2s', ['voteId']],
  [50, 'room.loadout', 'c2s', [['entries', map('loadout')], ['ops', map('ops')]]],
  [51, 'room.ownership', 'c2s', ['notOwned']],
  [52, 'room.diy', 'c2s', [['picks', map('diy')]]],
  [53, 'room.spectate', 'c2s', ['code']],
  [54, 'room.removeSpectator', 'c2s', ['playerId']],
  [55, 'g.infoReady', 'c2s', ['setupRevision']],
  [56, 'g.rerollVote', 'c2s', ['voteId', 'agree']],
  [57, 'g.band', 'c2s', ['bandId', 'draftId', 'groupId']],
  [58, 'g.bandSkip', 'c2s', ['draftId', 'groupId']],
  [59, 'g.bandFocus', 'c2s', ['bandId', 'draftId', 'groupId']],
  [60, 'g.buy', 'c2s', ['slot']],
  [61, 'g.refresh', 'c2s', []],
  [62, 'g.freeze', 'c2s', []],
  [63, 'g.levelUp', 'c2s', []],
  [64, 'g.sell', 'c2s', ['uid']],
  [65, 'g.move', 'c2s', ['uid', ['to', 'moveTarget'], ['dir', en('dir')]]],
  [66, 'g.equip', 'c2s', ['itemUid', 'targetUid', 'replaceUid']],
  [67, 'g.art', 'c2s', ['itemUid', 'row', 'col', ['dir', en('dir')]]],
  [68, 'g.destroy', 'c2s', ['uid']],
  [69, 'g.reward', 'c2s', ['idx']],
  [70, 'g.choice', 'c2s', ['idx', 'choiceId', 'draftId', 'groupId']],
  [71, 'g.ready', 'c2s', ['ready']],
  [72, 'g.emote', 'c2s', ['id']],
  [73, 'g.watch', 'c2s', ['fieldId', 'playerId']],
  [74, 'g.autoplay', 'c2s', ['on']],
  [75, 'g.pause', 'c2s', ['on']],
  [76, 'g.uniteSkipVote', 'c2s', ['voteId']],
  [77, 'g.unitStats', 'c2s', ['seq']],
  [78, 'g.leave', 'c2s', []],
  [79, 'b.progress', 'c2s', ['battleId', 'gt', 'killed', 'total', 'resolved', 'leaks', 'bossDmg', 'by', 'done', 'left', 'leaksBy']],
  [80, 'b.result', 'c2s', ['battleId', ['result', 'battleResult']]],
  [81, 'b.yield', 'c2s', ['battleId']],
];

// Deep-freeze the registry: mutation of a shared table would silently change the same numeric positions in flight.
function freeze(value) {
  if (value && typeof value === 'object' && !Object.isFrozen(value)) {
    for (const child of Object.values(value)) freeze(child);
    Object.freeze(value);
  }
  return value;
}
freeze(WIRE_RECORDS);
freeze(WIRE_MESSAGES);
